### ISSUE TITLE
Provide first simple tests

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-SV#34]
The [current version](https://github.com/MEPP-team/UDV/commits/master) of the [first prototype (Vilo3D demo application)](https://github.com/MEPP-team/UDV/tree/master/Vilo3D) misses some simple tests.
At least provide dummy test introducing the testing framework (refer to iTowns for examples?).

**Comment by EricBoix** [comment]
Comparisons:
 - [Raygun's](https://raygun.com/blog/javascript-unit-testing-frameworks/) conclusion: [Tape](https://github.com/substack/tape) is simple (thus nice), [Mocha](https://mochajs.org/) has a steeper learning curve but is the most popular, [Jtest](https://facebook.github.io/jest/) is efficient on large project while being not too hard to kickstart. 

### Notes
 - You can [test your frontend (with Chrome) on Travis](https://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647) (with the Karma-runner). 
 - You seem to need a [test runner](https://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647) e.g. [Karma-runner](http://karma-runner.github.io/0.12/index.html) that seems to be "testing framework agnostic".

**Comment by jailln** [comment]
I have a small experience with client testing with [mocha](https://mochajs.org/) and [pupeeter](https://github.com/puppeteer/puppeteer) since it is used in itowns; i'll try to setup the framework since I think we really need this feature if we don't want to start loosing functionalities...

**Comment by EricBoix** [comment]
Concerning the usage of mocha within iTowns start with the [results of this search](https://github.com/iTowns/itowns/search?q=mocha) ?

**Comment by mathieuLivebardon** [comment]
There is currently no functional test system implemented in UD-Viz, however a document has been produced to keep track of the work already done and explain the problems encountered.

[MyTestSystem.md](https://github.com/VCityTeam/VCity/blob/master/MyTestSystem.md)
