### ISSUE TITLE
Provide means for creating and visualizing a hierarchical and temporal 3D Tiles tileset

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-SV#48]
## The problem

We want to be able to create and visualize a 3D Tiles tileset which represents hierarchical relationships between city objects and the evolution of the city in time (i.e. temporal dimension). 3D Tiles has been [extended](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/extensions) for [supporting the hierarchy between city objects](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/extensions/3DTILES_batch_table_hierarchy) and for representing the temporal dimension of cities.

Some work has been done for implementing these two extensions:
 * Hierarchy:
     * backend: [UDV-Server](https://github.com/MEPP-team/UDV-server/blob/semantic_hierarchy/ExtractCityData/extract_city_semantic.py) and [py3dtiles](https://github.com/Jeremy-Gaillard/py3dtiles/tree/bt_hierarchy)
     * frontend: [iTowns](https://github.com/iTowns/itowns/tree/batchtable_hierarchy)
  * Temporal:
     * backend: [UDV-Server](https://github.com/MEPP-team/UDV-server/blob/master/ExtractCityData/extract_city_data.py) and [py3dtiles](https://github.com/MEPP-team/py3dtiles/tree/3dtiles-temporal-v2)
     * frontend: [iTowns](https://github.com/jailln/itowns/tree/3dtiles-temporal)

These works need to be merged (and eventually adapted/finished) to work together.

This issue implies the realization of the issue #21 .

## Repository organization
The target working repository branch structure with the `MEPP-Team/py3dtiles` fork
```
             |------------- bt_hierarchy (copy of JGA's and adaptation)
             |--------- temporal_v2        (current work of VJA)
             |
-------------X master
             |--------- WIP_hierarchy_and_temporal (ad-hoc blend of bt_hierarchy and temporal_v2)
```
 * Advantage: we keep bt_hierarchy separate for PR (and rebase) to Oslandia
 * Inconvenient: when bt_hierarchy of temporal_v2 progresses we have to "rebuild" (is [cherry picking](http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html) the best tool to do so?). This method might become really messy (and expensive) when conflicts appear...

## Implementation constraint: "modularity principle"
"Batch Table Hierarchy" and "Temporal" are [3DTiles extensions](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/extensions). The code realized for this issue should thus follow this extension "philosophy" and thus be thought as modular. 

For example the handling of the "Batch Table Hierarchy" within Py3DTiles should first organize the technical means for extensions support and then use the provided modular/extension mechanism to define the batch-table-hierarchy support.
As illustration of this (extension driven) modularity principle, probably that a recommendable importation (python) command for enabling/importing bath-table-hierarchy support should be of the form
```
import core, extension-batch_table_hierarchy from py3dtiles
```  

## Actions
The back-end side:
 * [x] Finish JGA's extension of py3DTiles with batch table hierarchy.
        Note: the current reference repository is [branch bt_hierarchy JGA's py3dtiles fork](https://github.com/Jeremy-Gaillard/py3dtiles/tree/bt_hierarchy). Copy this branch (IP is ok since JGA's was at LIRIS at that time) to [MEPP-Team's Py3dtiles fork](https://github.com/MEPP-team/py3dtiles)
 * [x] when above "batch table hierarchy" support within Py3DTiles is finished PR resulting `bt_hierarchy` to Oslandia's master
 * [x] refactor the [`temporal_v2` branch](https://github.com/MEPP-team/py3dtiles/tree/3dtiles-temporal-v2) to follow above mentioned "modularity principle" 
 * [ ] At any working time manually create (with a cherry picking script?) a `WIP_hierarchy_and_temporal` branch that blends (the commits of) the branches `bt_hierarchy` and `temporal_v2`. Use WIP_hierarchy_and_temporal to work on `UDV-server-script`see below
 * [ ] develop a new `UDV-server-script` (based on `WIP_hierarchy_and_temporal`) that blends the following two processes
       - the exportation of semantic/hierarchical tile-sets: [JGA's extract_city_semantic.py](https://github.com/MEPP-team/UDV-server/blob/semantic_hierarchy/ExtractCityData/extract_city_semantic.py) (on `semantic_hierarchy` branch) 
       - the exportation of temporal tile-sets: based on [extract_city_data.py](https://github.com/MEPP-team/UDV-server/blob/master/ExtractCityData/extract_city_data.py), that initializes the process through the creation of a [materialized view](https://github.com/MEPP-team/UDV-server/blob/master/ExtractCityData/extract_city_data.py#L107), combined with [Py3DTiles's export_tileset](https://github.com/MEPP-team/py3dtiles/blob/3dtiles-temporal-v2/tools/export_tileset) 
   **Note**: the target approach/architecture/strategy for producing hierarchical together with temporal tile-sets should be the one of [JGA's extract_city_semantic.py](https://github.com/MEPP-team/UDV-server/blob/semantic_hierarchy/ExtractCityData/extract_city_semantic.py) (i.e. we use py3DTiles without building a temporary `3DCityView` database view

The front end side:
 * [x] Finish JGA's WIP as set in [iTowns' `batch_table_hierarchy` branch](https://github.com/iTowns/itowns/tree/batchtable_hierarchy)
   Note: make sure that [JGA's iTowns fork](https://github.com/Jeremy-Gaillard/itowns2) is aligned with [iTowns' `batch_table_hierarchy` branch](https://github.com/iTowns/itowns/tree/batchtable_hierarchy)
 * [x] launch an iTowns PR on resulting `batch_table_hierarchy` branch.
 * [ ] realize the blending of the above resulting iTowns batch_table_hierarchy adaptations with [`3dtiles-temporal` branch of VJA' iTowns fork](https://github.com/jailln/itowns/tree/3dtiles-temporal).
    Note: depending on the success of the above described ad-hoc merging branch strategy (for having at hand a Py3DTiles branch that gathers both hierarchy and temporal extensions) adopt the same one or find something else.

**Comment by EricBoix** [comment]
Test the tiler with a composition of BTH and (inclusive) temporal
