### ISSUE TITLE
Provide means for street adress geolocation

### ISSUE THREAD

**Issue by jailln** [VCityTeam/UD-SV#49]
References:

* [Need](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need024.md)
* [Design Note](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Design/DesignNote024.md)

**Comment by Crejak** [comment]
Geocoding can be easily performed by calling web services. Most of them are free (at least until a certain amount of requests) but require authentication (through API keys, for example) :

* Google : https://developers.google.com/maps/documentation/geocoding/
* OpenCage : https://opencagedata.com/api
* MapQuest : https://developer.mapquest.com/documentation/open/geocoding-api/
* Geocodio : https://www.geocod.io/
* others...

**Comment by jailln** [comment]
Done in [VCityTeam/UD-Viz#84](https://github.com/VCityTeam/UD-Viz/pull/84)
