### ISSUE TITLE
Realize the database modeling of temporal dimension of city models (N10)

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-SV#6]
**Assignement lead**: EBO

Refer to [need 10](https://github.com/MEPP-team/RICT/blob/master/Doc/Devel/Needs/Need010.md)

**Comment by johnsamuelwrites** [comment]
After a discussion with Eric, we decided to look at creating a solution in the following manner:
1. Use the existing 3DcityDB model and generate DDL statements (e.g. using pgadmin).
2. Make changes to 3DCityDB model to incorporate temporal dimension of city models.
3. Generate DDL statements.
4. Share the difference between this new DDL and the previous ones.

**Comment by EricBoix** [comment]
Could you please provide some input on the advancement of this issue?

**Comment by johnsamuelwrites** [comment]
Currently, we are focusing on GIT based solution to handle temporal aspects, i.e., a solution without changing the CityGML model. Based on the results, we will see if we need to change the model. So, this work is currently on hold.

**Comment by jailln** [comment]
@johnsamuelwrites I don't see this be done in the near future, do you agree on closing this issue ?

**Comment by johnsamuelwrites** [comment]
@jailln I think that we can close this issue, considering the fact that CityGML 3.0 will be released soon.
