### ISSUE TITLE
Finish the itwons tutorial (and remove the old one)

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-SV#63]
They are currently two tutorials:
 - [Tutorial.md](https://github.com/MEPP-team/RICT/blob/master/UD-Doc/iTowns/Tutorial.md) in french
 - [iTowns_tutorial.md](https://github.com/MEPP-team/RICT/blob/master/UD-Doc/iTowns/iTowns_tutorial.md) looks based on the first one but in english and more recent yet marked as WIP.

Finish this conversion work an remove what needs to be removed.

**Comment by thomleysens** [comment]
I didn't write the tutorial in french. Don't know what to do with it. 
The english one is marked "UNDER CONSTRUCTION" (*as requested by GGE*) but I'm done with it for now and I don't have anything to add.

**Comment by EricBoix** [comment]
Check out that all the content of the french version got translated to the english version.
Archive the french version.
Remove the WIP from the english one.

**Comment by SakinaZeghloul** [comment]
Hello, I followed the tutorial. But I don't know why it doesn't work. I've got this mistake: "Error: New WMTSSource: projection is required".

**Comment by jailln** [comment]
Done in #65
