### ISSUE TITLE
Remove the VCity fork of libcityGML

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-SV#68]
Do we still need the https://github.com/VCityTeam/libcitygml repository ?

References: 
 * a VCity made comparison of [different libcityGML strains](https://github.com/VCityTeam/VCity/wiki/libCityGML_NG) 
 * [Related issue #68](https://github.com/VCityTeam/VCity/issues/68)
 * [Other related issue #160](https://github.com/VCityTeam/VCity/issues/160)

MTO said:
```
Ce fork était utilisé soit dans 3duse soit dans le petit logiciel de découpage des cartes/plans annexe mais 
donc dans le repo 3duse aussi...
Je ne me souviens que de cela 5 ans 1/2 après...
```

**Comment by ggesquiere** [comment]
If we want to make a process, data are read with this lib. It may be an issue to replace the reader by a simple query on 3DCityDB

**Comment by EricBoix** [comment]
After discussion with GGE, and as indirectly stated by [this libcityGML strains comparison](https://github.com/VCityTeam/VCity/wiki/libCityGML_NG), 3DUSE does not use J. Klimke library, but a version directly derived from the BRGM strain. We can thus remove the concerned repository.

**Comment by ggesquiere** [comment]
Checked. We can remove this directory. I reopen another issue linked to this https://github.com/VCityTeam/VCity/issues/241
